import { StyleSheet } from "react-native";
import { colors, radius, shadow, spacing, typography } from "../theme/tokens";

export const gameStyles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: colors.base.background,
  },
  screen: {
    flexGrow: 1,
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.x2,
    paddingBottom: 110,
    gap: spacing.md,
  },
  title: {
    fontSize: typography.size.titleMd,
    fontWeight: typography.weight.bold,
    color: colors.base.text,
  },
  description: {
    fontSize: typography.size.bodyLg,
    lineHeight: typography.lineHeight.bodyLg,
    color: colors.base.textSubtle,
  },
  cardTitle: {
    fontSize: typography.size.labelLg,
    fontWeight: typography.weight.bold,
    color: colors.base.text,
  },
  cardBody: {
    fontSize: typography.size.bodySm,
    color: colors.base.textSubtle,
  },
  moreBtn: {
    alignSelf: "center",
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
  },
  moreText: {
    color: colors.brand[700],
    fontWeight: typography.weight.semibold,
  },
  listHeader: {
    gap: spacing.md,
  },
  mapScreen: {
    flex: 1,
  },
  mapBody: {
    flex: 1,
  },
  mapFull: {
    flex: 1,
    width: "100%",
  },
  floatingBottomLeftControls: {
    position: "absolute",
    left: spacing.xl,
    bottom: spacing.x3,
    gap: spacing.sm,
    zIndex: 11,
    elevation: 4,
  },
  floatingBottomRightCluster: {
    position: "absolute",
    right: spacing.xl,
    bottom: spacing.x3,
    gap: spacing.sm,
    zIndex: 11,
    elevation: 4,
  },
  sparkRow: {
    alignItems: "flex-end",
  },
  bottomRightRow: {
    flexDirection: "row",
    gap: spacing.sm,
  },
  floatingCircleButton: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: colors.base.surface,
    borderWidth: 1,
    borderColor: colors.base.border,
    alignItems: "center",
    justifyContent: "center",
    ...shadow.level2,
  },
  floatingListButtonWide: {
    minHeight: 46,
    borderRadius: radius.pill,
    backgroundColor: colors.base.surface,
    borderWidth: 1,
    borderColor: colors.base.border,
    paddingHorizontal: spacing.md,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.xs,
    ...shadow.level2,
  },
  floatingListButtonLabel: {
    color: colors.base.text,
    fontSize: typography.size.labelMd,
    fontWeight: typography.weight.bold,
  },
  sheetBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(10, 12, 10, 0.35)",
    zIndex: 12,
  },
  sheetPanel: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: "62%",
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    backgroundColor: colors.base.surface,
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderColor: colors.base.border,
    zIndex: 13,
    overflow: "hidden",
  },
  placeDetailSheetPanel: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: "72%",
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    backgroundColor: colors.base.surface,
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderColor: colors.base.border,
    zIndex: 14,
    overflow: "hidden",
  },
  placeDetailSheetContent: {
    paddingHorizontal: spacing.xl,
    paddingBottom: spacing.x3,
    gap: spacing.md,
  },
  placeDetailCollapsedContent: {
    paddingHorizontal: spacing.xl,
    paddingBottom: spacing.md,
  },
  placeDetailSheetHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  sheetHandle: {
    width: 48,
    height: 5,
    borderRadius: 3,
    backgroundColor: colors.base.subtle,
    alignSelf: "center",
    marginTop: spacing.sm,
    marginBottom: spacing.sm,
  },
  sheetHandleTouch: {
    paddingTop: spacing.xs,
    paddingBottom: spacing.xs,
  },
  sheetHeader: {
    padding: spacing.md,
    gap: spacing.xs,
    borderTopColor: colors.base.border,
    backgroundColor: colors.base.surface,
  },
  sheetHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  sheetList: {
    paddingHorizontal: spacing.xl,
    paddingBottom: spacing.xl,
    gap: spacing.sm,
  },
  mapWrap: {
    borderRadius: 14,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#E1E6DE",
    backgroundColor: colors.base.surface,
  },
  map: {
    width: "100%",
    height: 260,
  },
  mapMetaRow: {
    position: "absolute",
    left: spacing.xl,
    right: spacing.xl,
    top: spacing.lg,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: radius.md,
    backgroundColor: "rgba(255, 255, 255, 0.92)",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: spacing.sm,
    zIndex: 9,
  },
  floatingPlaceCard: {
    position: "absolute",
    left: spacing.xl,
    right: spacing.xl,
    bottom: spacing.lg,
    borderRadius: radius.lg,
    backgroundColor: "rgba(255, 255, 255, 0.96)",
    borderWidth: 1,
    borderColor: colors.base.border,
    padding: spacing.md,
    gap: spacing.sm,
    zIndex: 12,
    ...shadow.level2,
  },
  floatingPlaceTop: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  floatingPlaceImage: {
    width: 56,
    height: 56,
    borderRadius: radius.md,
    backgroundColor: colors.base.subtle,
  },
  floatingPlaceImageFallback: {
    width: 56,
    height: 56,
    borderRadius: radius.md,
    backgroundColor: colors.base.subtle,
    alignItems: "center",
    justifyContent: "center",
  },
  floatingPlaceTextWrap: {
    flex: 1,
    gap: 2,
  },
  locationErrorModal: {
    position: "absolute",
    left: spacing.xl,
    right: spacing.xl,
    top: "30%",
    borderRadius: radius.lg,
    backgroundColor: colors.base.surface,
    borderWidth: 1,
    borderColor: colors.base.border,
    padding: spacing.lg,
    gap: spacing.md,
    zIndex: 20,
    ...shadow.level2,
  },
  listFooter: {
    paddingVertical: spacing.md,
    gap: spacing.xs,
  },
  endText: {
    textAlign: "center",
    color: colors.base.textSubtle,
    fontSize: typography.size.bodySm,
  },
  backBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    alignSelf: "flex-start",
  },
  backText: {
    color: colors.base.text,
    fontSize: typography.size.bodySm,
    fontWeight: typography.weight.medium,
  },
  placeImage: {
    width: "100%",
    height: 220,
    borderRadius: 14,
    backgroundColor: colors.base.surface,
  },
  imageFallback: {
    height: 160,
    borderRadius: 14,
    backgroundColor: colors.base.surface,
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.xs,
  },
  detailLabel: {
    color: colors.base.text,
    fontWeight: typography.weight.semibold,
    marginBottom: spacing.xs,
    fontSize: typography.size.bodySm,
  },
  errorText: {
    color: "#B42318",
    fontSize: typography.size.bodySm,
  },
  collectionScreen: {
    flex: 1,
    paddingTop: spacing.sm,
    paddingHorizontal: spacing.lg,
  },
  collectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: spacing.lg,
  },
  collectionHeaderTitle: {
    fontSize: 46 / 2,
    lineHeight: 56 / 2,
    fontWeight: typography.weight.bold,
    color: "#111827",
  },
  collectionHeaderIconBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  collectionProgressCard: {
    borderRadius: radius.xl,
    borderWidth: 1,
    borderColor: colors.base.border,
    backgroundColor: colors.base.surface,
    padding: spacing.lg,
    gap: spacing.md,
  },
  collectionProgressTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.md,
  },
  collectionProgressTextWrap: {
    flex: 1,
    gap: spacing.xs,
  },
  collectionProgressLevel: {
    color: "#15C85F",
    fontSize: typography.size.titleSm,
    fontWeight: typography.weight.semibold,
  },
  collectionProgressTitle: {
    color: "#0F172A",
    fontSize: (22 / 2) * 2,
    fontWeight: typography.weight.bold,
  },
  collectionProgressTrophyWrap: {
    width: 84,
    height: 84,
    borderRadius: 42,
    backgroundColor: "#E8F6EC",
    alignItems: "center",
    justifyContent: "center",
  },
  collectionProgressTrack: {
    height: 20,
    borderRadius: 10,
    backgroundColor: "#D9E0DB",
    overflow: "hidden",
  },
  collectionProgressFill: {
    height: "100%",
    borderRadius: 10,
    backgroundColor: "#15D85C",
  },
  collectionProgressPercent: {
    alignSelf: "flex-end",
    color: "#52607A",
    fontSize: typography.size.titleSm,
    fontWeight: typography.weight.medium,
  },
  collectionTabsRow: {
    paddingTop: spacing.lg,
    paddingBottom: spacing.md,
    gap: spacing.sm,
    alignItems: "center",
  },
  collectionTabsWrap: {
    height: 82,
  },
  collectionTabsScroll: {
    flexGrow: 0,
  },
  collectionTabChip: {
    minWidth: 136,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.base.border,
    backgroundColor: colors.base.surface,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    alignSelf: "center",
  },
  collectionTabChipActive: {
    borderColor: "#9BE8B9",
    backgroundColor: "#C9F3DB",
  },
  collectionTabChipInner: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.sm,
  },
  collectionTabChipLabel: {
    color: "#52607A",
    fontSize: typography.size.titleSm,
    fontWeight: typography.weight.medium,
  },
  collectionTabChipLabelActive: {
    color: colors.brand[800],
    fontWeight: typography.weight.semibold,
  },
  collectionGridContent: {
    paddingTop: spacing.sm,
    paddingBottom: 120,
    gap: spacing.md,
  },
  collectionGridFooter: {
    paddingVertical: spacing.md,
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.xs,
  },
  collectionGridRow: {
    gap: spacing.md,
  },
  collectionCardWrap: {
    flex: 1,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.base.border,
    backgroundColor: colors.base.surface,
    padding: spacing.md,
    gap: spacing.sm,
  },
  collectionCardImageWrap: {
    borderRadius: radius.lg,
    overflow: "hidden",
    height: 220,
    backgroundColor: colors.base.subtle,
    position: "relative",
    alignItems: "center",
    justifyContent: "center",
  },
  collectionCardImage: {
    width: "100%",
    height: "100%",
  },
  collectionCardImageFallback: {
    width: "100%",
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.base.subtle,
  },
  collectionRareBadge: {
    position: "absolute",
    top: spacing.sm,
    right: spacing.sm,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.base.surface,
    alignItems: "center",
    justifyContent: "center",
  },
  collectionCardName: {
    fontSize: 40 / 2,
    lineHeight: 48 / 2,
    color: "#0F172A",
    fontWeight: typography.weight.bold,
  },
  collectionCardStatus: {
    fontSize: typography.size.titleSm,
    color: "#15C85F",
    fontWeight: typography.weight.medium,
  },
  collectionCardImageLocked: {
    backgroundColor: "#AEB4BD",
  },
  collectionCardLockOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(21, 28, 39, 0.7)",
  },
  collectionCardLockCircle: {
    position: "absolute",
    width: 84,
    height: 84,
    borderRadius: 42,
    backgroundColor: "rgba(83, 92, 115, 0.52)",
    alignItems: "center",
    justifyContent: "center",
  },
  collectionCardNameLocked: {
    color: "#7C879A",
  },
  collectionCardStatusLocked: {
    fontSize: typography.size.titleSm,
    color: "#9AA3B2",
    fontWeight: typography.weight.medium,
  },
  collectionStateBox: {
    marginTop: spacing.x2,
    alignItems: "center",
    justifyContent: "center",
  },
});
