import { StyleSheet } from "react-native";
import { colors, radius, spacing, typography } from "../theme/tokens";

export const gameStyles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: colors.base.background,
  },
  screen: {
    flexGrow: 1,
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.x2,
    paddingBottom: 110,
    gap: spacing.md,
  },
  title: {
    fontSize: typography.size.titleLg,
    fontWeight: typography.weight.bold,
    color: colors.base.text,
  },
  description: {
    fontSize: typography.size.bodyLg,
    lineHeight: typography.lineHeight.bodyLg,
    color: colors.base.textSubtle,
  },
  cardTitle: {
    fontSize: typography.size.labelLg,
    fontWeight: typography.weight.bold,
    color: colors.base.text,
  },
  cardBody: {
    fontSize: typography.size.bodySm,
    color: colors.base.textSubtle,
  },
  moreBtn: {
    alignSelf: "center",
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
  },
  moreText: {
    color: colors.brand[700],
    fontWeight: typography.weight.semibold,
  },
  listHeader: {
    gap: spacing.md,
  },
  mapScreen: {
    flex: 1,
    paddingBottom: 110,
  },
  mapBody: {
    flex: 1,
  },
  mapFull: {
    flex: 1,
    width: "100%",
  },
  mapTopHeader: {
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.lg,
    paddingBottom: spacing.sm,
    backgroundColor: colors.base.background,
    gap: spacing.xs,
  },
  floatingListButton: {
    position: "absolute",
    right: spacing.xl,
    bottom: spacing.x3,
    minHeight: 46,
    borderRadius: radius.pill,
    backgroundColor: colors.base.surface,
    borderWidth: 1,
    borderColor: colors.base.border,
    paddingHorizontal: spacing.lg,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.xs,
    zIndex: 11,
    elevation: 4,
  },
  floatingListLabel: {
    color: colors.base.text,
    fontSize: typography.size.labelMd,
    fontWeight: typography.weight.bold,
  },
  sheetBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(10, 12, 10, 0.35)",
    zIndex: 12,
  },
  sheetPanel: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: "62%",
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    backgroundColor: colors.base.surface,
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderColor: colors.base.border,
    zIndex: 13,
    overflow: "hidden",
  },
  sheetHandle: {
    width: 48,
    height: 5,
    borderRadius: 3,
    backgroundColor: colors.base.subtle,
    alignSelf: "center",
    marginTop: spacing.sm,
    marginBottom: spacing.sm,
  },
  sheetHeader: {
    padding: spacing.md,
    gap: spacing.xs,
    borderTopColor: colors.base.border,
    backgroundColor: colors.base.surface,
  },
  sheetList: {
    paddingHorizontal: spacing.xl,
    paddingBottom: spacing.xl,
    gap: spacing.sm,
  },
  mapWrap: {
    borderRadius: 14,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#E1E6DE",
    backgroundColor: colors.base.surface,
  },
  map: {
    width: "100%",
    height: 260,
  },
  mapMetaRow: {
    position: "absolute",
    left: spacing.xl,
    right: spacing.xl,
    top: spacing.md,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: radius.md,
    backgroundColor: "rgba(255, 255, 255, 0.92)",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: spacing.sm,
    zIndex: 10,
  },
  listFooter: {
    paddingVertical: spacing.md,
    gap: spacing.xs,
  },
  endText: {
    textAlign: "center",
    color: colors.base.textSubtle,
    fontSize: typography.size.bodySm,
  },
  backBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    alignSelf: "flex-start",
  },
  backText: {
    color: colors.base.text,
    fontSize: typography.size.bodySm,
    fontWeight: typography.weight.medium,
  },
  placeImage: {
    width: "100%",
    height: 220,
    borderRadius: 14,
    backgroundColor: colors.base.surface,
  },
  imageFallback: {
    height: 160,
    borderRadius: 14,
    backgroundColor: colors.base.surface,
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.xs,
  },
  detailLabel: {
    color: colors.base.text,
    fontWeight: typography.weight.semibold,
    marginBottom: spacing.xs,
    fontSize: typography.size.bodySm,
  },
  errorText: {
    color: "#B42318",
    fontSize: typography.size.bodySm,
  },
});
